# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../dash.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(640, 480))
        MainWindow.setStyleSheet("background-color: rgb(61, 56, 70);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_row = QtWidgets.QHBoxLayout()
        self.top_row.setObjectName("top_row")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.top_row.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.top_row.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.top_row)
        self.middle_row = QtWidgets.QHBoxLayout()
        self.middle_row.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.middle_row.setObjectName("middle_row")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.middle_row.addItem(spacerItem2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"  color: white;\n"
"  font: 11pt \"American Kestrel Semi-Straight\";\n"
"    border: 1px solid white;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    top: -6px;\n"
"    left: 10px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mphLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mphLabel.sizePolicy().hasHeightForWidth())
        self.mphLabel.setSizePolicy(sizePolicy)
        self.mphLabel.setStyleSheet("font: 48pt \"American Kestrel Straight\";\n"
"color: rgb(246, 245, 244);")
        self.mphLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mphLabel.setObjectName("mphLabel")
        self.horizontalLayout_3.addWidget(self.mphLabel)
        self.middle_row.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"  color: white;\n"
"  font: 11pt \"American Kestrel Semi-Straight\";\n"
"    border: 1px solid white;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    top: -6px;\n"
"    left: 10px;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gearLabel = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gearLabel.sizePolicy().hasHeightForWidth())
        self.gearLabel.setSizePolicy(sizePolicy)
        self.gearLabel.setStyleSheet("color: white;\n"
"font: 64pt \"American Kestrel Straight\";\n"
"border: none;")
        self.gearLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gearLabel.setObjectName("gearLabel")
        self.horizontalLayout.addWidget(self.gearLabel)
        self.middle_row.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setStyleSheet("\n"
"QGroupBox{\n"
"  color: white;\n"
"  font: 11pt \"American Kestrel Semi-Straight\";\n"
"    border: 1px solid white;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    top: -6px;\n"
"    left: 10px;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ectLabel = QtWidgets.QLabel(self.groupBox_3)
        self.ectLabel.setStyleSheet("color: white;\n"
"font: 48pt \"American Kestrel Straight\";\n"
"border: none;")
        self.ectLabel.setObjectName("ectLabel")
        self.horizontalLayout_2.addWidget(self.ectLabel)
        self.middle_row.addWidget(self.groupBox_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.middle_row.addItem(spacerItem3)
        self.middle_row.setStretch(0, 1)
        self.middle_row.setStretch(1, 1)
        self.middle_row.setStretch(2, 1)
        self.middle_row.setStretch(4, 1)
        self.verticalLayout.addLayout(self.middle_row)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.canlabel201 = QtWidgets.QLabel(self.centralwidget)
        self.canlabel201.setStyleSheet("font: 14pt \"Monaco\";\n"
"color: white;\n"
"border: none;")
        self.canlabel201.setAlignment(QtCore.Qt.AlignCenter)
        self.canlabel201.setObjectName("canlabel201")
        self.gridLayout.addWidget(self.canlabel201, 0, 1, 1, 1)
        self.canlabel200 = QtWidgets.QLabel(self.centralwidget)
        self.canlabel200.setStyleSheet("font: 14pt \"Monaco\";\n"
"color: white;\n"
"border: none;")
        self.canlabel200.setAlignment(QtCore.Qt.AlignCenter)
        self.canlabel200.setObjectName("canlabel200")
        self.gridLayout.addWidget(self.canlabel200, 0, 0, 1, 1)
        self.canlabel420 = QtWidgets.QLabel(self.centralwidget)
        self.canlabel420.setStyleSheet("font: 14pt \"Monaco\";\n"
"color: white;\n"
"border: none;")
        self.canlabel420.setAlignment(QtCore.Qt.AlignCenter)
        self.canlabel420.setObjectName("canlabel420")
        self.gridLayout.addWidget(self.canlabel420, 1, 2, 1, 1)
        self.canlabel231 = QtWidgets.QLabel(self.centralwidget)
        self.canlabel231.setStyleSheet("font: 14pt \"Monaco\";\n"
"color: white;\n"
"border: none;")
        self.canlabel231.setAlignment(QtCore.Qt.AlignCenter)
        self.canlabel231.setObjectName("canlabel231")
        self.gridLayout.addWidget(self.canlabel231, 1, 0, 1, 1)
        self.canlabel211 = QtWidgets.QLabel(self.centralwidget)
        self.canlabel211.setStyleSheet("font: 14pt \"Monaco\";\n"
"color: white;\n"
"border: none;")
        self.canlabel211.setAlignment(QtCore.Qt.AlignCenter)
        self.canlabel211.setObjectName("canlabel211")
        self.gridLayout.addWidget(self.canlabel211, 0, 2, 1, 1)
        self.canlabel240 = QtWidgets.QLabel(self.centralwidget)
        self.canlabel240.setStyleSheet("font: 14pt \"Monaco\";\n"
"color: white;\n"
"border: none;")
        self.canlabel240.setAlignment(QtCore.Qt.AlignCenter)
        self.canlabel240.setObjectName("canlabel240")
        self.gridLayout.addWidget(self.canlabel240, 1, 1, 1, 1)
        self.canlabel212 = QtWidgets.QLabel(self.centralwidget)
        self.canlabel212.setStyleSheet("font: 14pt \"Monaco\";\n"
"color: white;\n"
"border: none;")
        self.canlabel212.setAlignment(QtCore.Qt.AlignCenter)
        self.canlabel212.setObjectName("canlabel212")
        self.gridLayout.addWidget(self.canlabel212, 0, 3, 1, 1)
        self.canlabel430 = QtWidgets.QLabel(self.centralwidget)
        self.canlabel430.setStyleSheet("font: 14pt \"Monaco\";\n"
"color: white;\n"
"border: none;")
        self.canlabel430.setAlignment(QtCore.Qt.AlignCenter)
        self.canlabel430.setObjectName("canlabel430")
        self.gridLayout.addWidget(self.canlabel430, 1, 3, 1, 1)
        self.canlabel215 = QtWidgets.QLabel(self.centralwidget)
        self.canlabel215.setStyleSheet("font: 14pt \"Monaco\";\n"
"color: white;\n"
"border: none;")
        self.canlabel215.setAlignment(QtCore.Qt.AlignCenter)
        self.canlabel215.setObjectName("canlabel215")
        self.gridLayout.addWidget(self.canlabel215, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rpmProgressbar = QtWidgets.QProgressBar(self.centralwidget)
        self.rpmProgressbar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rpmProgressbar.sizePolicy().hasHeightForWidth())
        self.rpmProgressbar.setSizePolicy(sizePolicy)
        self.rpmProgressbar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 36pt \"American Kestrel Semi-Straight\";")
        self.rpmProgressbar.setMaximum(7500)
        self.rpmProgressbar.setProperty("value", 6000)
        self.rpmProgressbar.setInvertedAppearance(False)
        self.rpmProgressbar.setObjectName("rpmProgressbar")
        self.verticalLayout_3.addWidget(self.rpmProgressbar)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "mph"))
        self.mphLabel.setText(_translate("MainWindow", "64"))
        self.groupBox_2.setTitle(_translate("MainWindow", "gear"))
        self.gearLabel.setText(_translate("MainWindow", "3"))
        self.groupBox_3.setTitle(_translate("MainWindow", "ect"))
        self.ectLabel.setText(_translate("MainWindow", "100"))
        self.canlabel201.setText(_translate("MainWindow", "ffffffff\n"
"ffffffff"))
        self.canlabel200.setText(_translate("MainWindow", "ffffffff\n"
"ffffffff"))
        self.canlabel420.setText(_translate("MainWindow", "ffffffff\n"
"ffffffff"))
        self.canlabel231.setText(_translate("MainWindow", "ffffffff\n"
"ffffffff"))
        self.canlabel211.setText(_translate("MainWindow", "ffffffff\n"
"ffffffff"))
        self.canlabel240.setText(_translate("MainWindow", "ffffffff\n"
"ffffffff"))
        self.canlabel212.setText(_translate("MainWindow", "ffffffff\n"
"ffffffff"))
        self.canlabel430.setText(_translate("MainWindow", "ffffffff\n"
"ffffffff"))
        self.canlabel215.setText(_translate("MainWindow", "ffffffff\n"
"ffffffff"))
        self.rpmProgressbar.setFormat(_translate("MainWindow", "%v"))
